// Package docs generates GSKILL's reference documentation from the live sources
// of truth — the Kong command grammar (internal/cli) and the exit-code table
// (internal/errs) — so the reference can never silently drift from the tool.
//
// The rendered Markdown is deterministic (sorted, timestamp-free) so it is
// safe to commit and golden-test. Regenerate with: go run ./cmd/gen-reference
package docs

import (
	"fmt"
	"sort"
	"strings"

	"github.com/alecthomas/kong"

	"github.com/glapsfun/gskill/internal/cli"
	"github.com/glapsfun/gskill/internal/errs"
)

// generatedHeader marks files produced by cmd/gen-reference so reviewers and
// editors know not to hand-edit them.
const generatedHeader = "<!-- GENERATED by cmd/gen-reference; DO NOT EDIT. Run: go run ./cmd/gen-reference -->"

// CommandsPath and ExitCodesPath are the repo-relative targets the generator writes.
const (
	CommandsPath  = "docs/reference/commands.md"
	ExitCodesPath = "docs/reference/exit-codes.md"
)

// RenderCommands builds the Markdown command reference from the Kong model.
// Output is deterministic: global flags first, then commands sorted by name,
// each with its flags sorted by name.
func RenderCommands(model *kong.Application) string {
	var b strings.Builder
	writeLine(&b, generatedHeader)
	writeLine(&b, "")
	writeLine(&b, "# Command reference")
	writeLine(&b, "")
	writeLine(&b, "Every `gskill` command and its flags, generated from the CLI grammar.")
	writeLine(&b, "")

	writeLine(&b, "## Global flags")
	writeLine(&b, "")
	writeLine(&b, "These apply to every command.")
	writeLine(&b, "")
	writeFlagTable(&b, model.Flags)

	cmds := append([]*kong.Node(nil), model.Children...)
	sort.Slice(cmds, func(i, j int) bool { return cmds[i].Name < cmds[j].Name })
	for _, cmd := range cmds {
		writeCommand(&b, cmd, cmd.Name)
	}
	return normalizeTrailing(b.String())
}

// normalizeTrailing guarantees exactly one trailing newline so the output is
// stable and agrees with the repo's end-of-file hook.
func normalizeTrailing(s string) string {
	return strings.TrimRight(s, "\n") + "\n"
}

// writeCommand renders one command node (and any one-level subcommands) using
// the fully-qualified name path (e.g. "cache list").
func writeCommand(b *strings.Builder, node *kong.Node, name string) {
	writeLine(b, "")
	writeLine(b, "## `"+name+"`")
	writeLine(b, "")
	if help := strings.TrimSpace(node.Help); help != "" {
		writeLine(b, help)
		writeLine(b, "")
	}
	if len(node.Positional) > 0 {
		writeLine(b, "| Argument | Required | Description |")
		writeLine(b, "| --- | --- | --- |")
		for _, p := range node.Positional {
			req := "no"
			if p.Required {
				req = "yes"
			}
			writeLine(b, fmt.Sprintf("| `%s` | %s | %s |", p.Name, req, oneLine(p.Help)))
		}
		writeLine(b, "")
	}
	if local := localFlags(node); len(local) > 0 {
		writeFlagTable(b, local)
	}

	subs := append([]*kong.Node(nil), node.Children...)
	sort.Slice(subs, func(i, j int) bool { return subs[i].Name < subs[j].Name })
	for _, sub := range subs {
		writeCommand(b, sub, name+" "+sub.Name)
	}
}

// localFlags returns a node's own flags, skipping the auto-added --help flag.
func localFlags(node *kong.Node) []*kong.Flag {
	out := make([]*kong.Flag, 0, len(node.Flags))
	for _, f := range node.Flags {
		if f.Name == "help" || f.Hidden {
			continue
		}
		out = append(out, f)
	}
	return out
}

// writeFlagTable writes a sorted Markdown table of flags, or a note if empty.
func writeFlagTable(b *strings.Builder, flags []*kong.Flag) {
	visible := make([]*kong.Flag, 0, len(flags))
	for _, f := range flags {
		if f.Name == "help" || f.Hidden {
			continue
		}
		visible = append(visible, f)
	}
	if len(visible) == 0 {
		writeLine(b, "_No flags._")
		writeLine(b, "")
		return
	}
	sort.Slice(visible, func(i, j int) bool { return visible[i].Name < visible[j].Name })

	writeLine(b, "| Flag | Type | Description |")
	writeLine(b, "| --- | --- | --- |")
	for _, f := range visible {
		writeLine(b, fmt.Sprintf("| `--%s` | %s | %s |", f.Name, flagType(f), oneLine(f.Help)))
	}
	writeLine(b, "")
}

// flagType reports a flag's value type for the reference table.
func flagType(f *kong.Flag) string {
	if f.IsBool() {
		return "bool"
	}
	if f.Value != nil && f.Target.IsValid() {
		return f.Target.Type().String()
	}
	return "string"
}

// RenderExitCodes builds the Markdown exit-code reference from the errs table.
// Codes are emitted in numeric order; their numbers come from internal/errs so
// they cannot diverge from the tool's actual contract.
func RenderExitCodes() string {
	type entry struct {
		code    errs.Code
		meaning string
	}
	// Meanings document the codes defined in internal/errs (numbers are sourced
	// from the errs constants, so the table stays aligned with the tool).
	entries := []entry{
		{errs.CodeOK, "success"},
		{errs.CodeGeneric, "generic or unexpected error"},
		{errs.CodeUsage, "usage error (bad flags or arguments)"},
		{errs.CodeInvalidManifest, "invalid manifest"},
		{errs.CodeLockMismatch, "lockfile mismatch (`--frozen-lockfile` would change)"},
		{errs.CodeSourceUnavailable, "source unavailable or network failure"},
		{errs.CodeIntegrity, "integrity failure (checksum mismatch)"},
		{errs.CodeDrift, "drift detected (`--fail-on-drift`)"},
		{errs.CodeUpdateAvailable, "update available (`outdated --exit-code`)"},
		{errs.CodeUnsupportedAgent, "unsupported or undetected agent"},
		{errs.CodePartialInstall, "partial installation"},
		{errs.CodeAuth, "authentication failure"},
		{errs.CodeCacheLock, "cache or lock failure (incl. lock-acquire timeout)"},
	}
	sort.SliceStable(entries, func(i, j int) bool { return entries[i].code < entries[j].code })

	var b strings.Builder
	writeLine(&b, generatedHeader)
	writeLine(&b, "")
	writeLine(&b, "# Exit codes")
	writeLine(&b, "")
	writeLine(&b, "Every `gskill` command exits with one of these codes. Scripts and CI can branch on them.")
	writeLine(&b, "")
	writeLine(&b, "| Code | Meaning |")
	writeLine(&b, "| --- | --- |")
	for _, e := range entries {
		writeLine(&b, fmt.Sprintf("| %d | %s |", int(e.code), e.meaning))
	}
	return normalizeTrailing(b.String())
}

// RenderAll renders both reference documents, returning them keyed by repo path.
func RenderAll() (map[string]string, error) {
	model, err := cli.DocsModel()
	if err != nil {
		return nil, fmt.Errorf("build docs model: %w", err)
	}
	return map[string]string{
		CommandsPath:  RenderCommands(model),
		ExitCodesPath: RenderExitCodes(),
	}, nil
}

// writeLine writes s and a single LF, normalizing line endings for determinism.
func writeLine(b *strings.Builder, s string) {
	b.WriteString(s)
	b.WriteByte('\n')
}

// oneLine collapses internal whitespace so a help string fits one table cell.
func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}
