// Package active manages the project active-skill layer: the per-skill entry at
// .agents/skills/<name> that links into the content store and is the single
// source of truth every agent target derives from.
//
// The three layers gskill maintains are:
//
//	.gskill/store/<algo>/<hash>   immutable canonical content (one physical copy)
//	          ▲ symlink (copy fallback)
//	.agents/skills/<name>          active project skill (one per installed skill)
//	          ▲ symlink (copy fallback)
//	.<agent>/skills/<name>         per-agent targets (claude, codex, cursor, …)
//
// The active layer holds no independent copy of the content: it links into the
// store, so adding an agent is one cheap link and a skill shared by N agents
// still exists exactly once on disk. The active layer is gitignored and
// regenerated by `gskill sync` from the committed manifest + lockfile.
package active
